
package com.dorayakisupplier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DorayakiSupplier", targetNamespace = "http://topdown.server.jaxws.baeldung.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DorayakiSupplier {


    /**
     * 
     * @param requestTime
     * @param code
     * @param jumlah
     * @param data
     * @param namaDorayaki
     * @param message
     * @param idDorayaki
     */
    @WebMethod(action = "requestDorayaki")
    @RequestWrapper(localName = "requestDorayaki", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.RequestDorayaki")
    @ResponseWrapper(localName = "requestDorayakiResponse", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.RequestDorayakiResponse")
    public void requestDorayaki(
        @WebParam(name = "idDorayaki", targetNamespace = "")
        int idDorayaki,
        @WebParam(name = "namaDorayaki", targetNamespace = "")
        String namaDorayaki,
        @WebParam(name = "jumlah", targetNamespace = "")
        int jumlah,
        @WebParam(name = "requestTime", targetNamespace = "")
        XMLGregorianCalendar requestTime,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DorayakiData> data);

    /**
     * 
     * @param requestTime
     * @param code
     * @param data
     * @param message
     */
    @WebMethod(action = "getStatusRequest")
    @RequestWrapper(localName = "getStatusRequest", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.GetStatusRequest")
    @ResponseWrapper(localName = "requestDorayakiResponse", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.RequestDorayakiResponse")
    public void getStatusRequest(
        @WebParam(name = "requestTime", targetNamespace = "")
        XMLGregorianCalendar requestTime,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DorayakiData> data);

    /**
     * 
     * @param requestTime
     * @param code
     * @param data
     * @param message
     */
    @WebMethod(action = "getListVariant")
    @RequestWrapper(localName = "getListVariant", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.GetListVariant")
    @ResponseWrapper(localName = "variantListResponse", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", className = "com.dorayakisupplier.VariantListResponse")
    public void getListVariant(
        @WebParam(name = "requestTime", targetNamespace = "")
        XMLGregorianCalendar requestTime,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<VariantList> data);

}
